
species: hg38
process_profiles: TRUE
start_new: TRUE

factor_hit_names: 
  - tf
  - not sure
  - predicted transcription factor
  - predicted chromatin regulator
  - cr
  - both predicted transcription factor and chromatin regulator
  - other 
  - None

chromatin_profiles: 
  - DNase
  - H3K27ac
  - ATAC

motif_data: "data/{species}_motifs.tsv"

cistrome_data: data/DC_haveProcessed_20190506_filepath_qc.xls

bigWigAverageOverBed_path: bigWigAverageOverBed